From Strang's Introduction to Linear Algebra, 5th ed., pp. 239.



In [ ]:
import numpy as np

In [ ]:
A = np.array([[1.0, 2.0], [5., -1.]])

In [ ]:
np.linalg.norm(A)

5.5677643628300215

In [ ]:
def GramSchmidt(A):
    Q = A.copy()
    R = np.zeros(A.shape)
    n, _ = A.shape
    for j in range(n):
        v = A[:,[j]].copy()            # (n,1)
        for i in range(j):
            R[i,j] = Q[:,[i]].T @ v
            v = v - R[i,j] * Q[:,[i]]
        R[j,j] = np.linalg.norm(v)
        Q[:,[j]] = v / R[j,j]
    return Q, R


In [ ]:
Q, R = GramSchmidt(A)

In [ ]:
Q

array([[ 0.19611614,  0.98058068],
       [ 0.98058068, -0.19611614]])

In [ ]:
R

array([[ 5.09901951, -0.58834841],
       [ 0.        ,  2.15727749]])

In [ ]:
Q[:,[0]].T @ Q[:,[0]]

array([[1.]])

In [ ]:
Q[:,[1]].T @ Q[:,[1]]

array([[1.]])

In [ ]:
Q[:,[0]].T @ Q[:,[1]]

array([[2.77555756e-17]])

Almost $0$.
It seems right!
Wow!!!

I'm tired.

Next, I'll check it more thoroughly.

In [ ]:
A = np.array([[1.0, 2.0, 1], [5., -1., 0], [2.3, 4, 1]])

In [ ]:
Q, R = GramSchmidt(A)

In [ ]:
Q

array([[ 0.17877106,  0.40522831,  0.89656618],
       [ 0.89385531, -0.44770613,  0.02412286],
       [ 0.41117344,  0.79708797, -0.44225238]])

In [ ]:
R

array([[5.59374651, 1.10838058, 0.5899445 ],
       [0.        , 4.44651465, 1.20231629],
       [0.        , 0.        , 0.45431381]])

In [ ]:
Q @ R - A

array([[ 0.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.11022302e-16,  3.71129946e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [ ]:
Q.T @ Q

array([[ 1.00000000e+00,  7.29018875e-18, -1.85365942e-16],
       [ 7.29018875e-18,  1.00000000e+00, -4.56952144e-16],
       [-1.85365942e-16, -4.56952144e-16,  1.00000000e+00]])

It's correct!!!

Right in the first time!!!